# Generated by Django 3.2 on 2022-09-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='商品名')),
                ('image', models.ImageField(db_index=True, upload_to='templates/static/upload_to/', verbose_name='商品画像')),
                ('now_price', models.CharField(db_index=True, max_length=50, verbose_name='現在の価格')),
                ('hope_price', models.CharField(db_index=True, max_length=50, verbose_name='希望価格')),
                ('recent_average', models.CharField(db_index=True, max_length=50, verbose_name='直近の平均価格')),
                ('fluctuating_value', models.CharField(db_index=True, max_length=50, verbose_name='変動値')),
                ('url', models.CharField(db_index=True, max_length=200, verbose_name='URL')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品マスタ',
            },
        ),
    ]
