# Generated by Django 3.2 on 2022-09-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='fluctuating_value',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='変動値'),
        ),
        migrations.AlterField(
            model_name='item',
            name='recent_average',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='直近の平均価格'),
        ),
    ]
