# Generated by Django 3.2 on 2022-09-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20220904_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(db_index=True, max_length=500, verbose_name='商品名'),
        ),
        migrations.AlterField(
            model_name='item',
            name='url',
            field=models.CharField(db_index=True, max_length=1000, verbose_name='URL'),
        ),
    ]
