# Generated by Django 3.2 on 2022-12-16 09:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_item_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 9, 59, 17, 602593, tzinfo=utc), verbose_name='更新日時'),
        ),
    ]
