# Generated by Django 3.2 on 2022-12-16 10:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_alter_item_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 10, 48, 0, 271799, tzinfo=utc), verbose_name='更新日時'),
        ),
        migrations.CreateModel(
            name='CacheItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.CharField(db_index=True, max_length=50, verbose_name='更新前の値段')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 12, 16, 10, 48, 0, 272113, tzinfo=utc), verbose_name='作成日時')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
            ],
            options={
                'verbose_name': '蓄積された値段',
                'verbose_name_plural': '値段蓄積マスタ',
            },
        ),
    ]
