# Generated by Django 3.2 on 2022-12-16 11:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_auto_20221216_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cacheitems',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 11, 12, 3, 720500, tzinfo=utc), verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 11, 12, 3, 719990, tzinfo=utc), verbose_name='更新日時'),
        ),
    ]
