# Generated by Django 3.2 on 2022-12-20 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_auto_20221216_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='recent_average',
        ),
    ]
